<?php

namespace App\Constants;

return [
    'DESIGNS_IMAGE_MAX_SIZE'=>'2048',
    'DESIGNS_IMAGE_MIN_SIZE'=>'10',

    'REQUISITION_IMAGE_MAX_SIZE'=>'2048',
    'REQUISITION_IMAGE_MIN_SIZE'=>'10',

    'STORE_RECEIPT_IMAGE_MAX_SIZE'=>'2048',
    'STORE_RECEIPT_IMAGE_MIN_SIZE'=>'10',

    'FINANCE_DOCUMENT_IMAGE_MAX_SIZE'=>'2048',
    'FINANCE_DOCUMENT_IMAGE_MIN_SIZE'=>'10',
    
    'GRN_IMAGE_MAX_SIZE'=>'2048',
    'GRN_IMAGE_MIN_SIZE'=>'10',

    'PURCHASE_ORDER_IMAGE_MAX_SIZE'=>'2048',
    'PURCHASE_ORDER_IMAGE_MIN_SIZE'=>'10',
    
];